<a href="https://colab.research.google.com/github/vaishnavimanohar/manoharvaishnavi.github./blob/main/vaishnavimanoharpythonanddeeplearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Artificial Neural Networks**

In [37]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense
import numpy as np

**Creating dataset for an AND Gate**

In [38]:
x = np.array([[0,0], [0,1], [1,0], [1,1]], "uint8")
y = np.array([[0], [0], [0], [1]], "uint8")

**Creating a Sequential model using Tensorflow**

In [39]:
model = Sequential()
model.add(Dense(units=1, activation='sigmoid', input_dim=2))  ## MODEL CONTAINS ONLY ONE OUTPUT NEURON
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


Add image (input and output)

In [40]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [46]:
model.fit(x, y, epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 6ms/step - loss: 0.4654 - accuracy: 1.0000
Epoch 2/500
1/1 [==============================] - 0s 7ms/step - loss: 0.4653 - accuracy: 1.0000
Epoch 3/500
1/1 [==============================] - 0s 4ms/step - loss: 0.4652 - accuracy: 1.0000
Epoch 4/500
1/1 [==============================] - 0s 9ms/step - loss: 0.4651 - accuracy: 1.0000
Epoch 5/500
1/1 [==============================] - 0s 5ms/step - loss: 0.4650 - accuracy: 1.0000
Epoch 6/500
1/1 [==============================] - 0s 5ms/step - loss: 0.4649 - accuracy: 1.0000
Epoch 7/500
1/1 [==============================] - 0s 7ms/step - loss: 0.4648 - accuracy: 1.0000
Epoch 8/500
1/1 [==============================] - 0s 8ms/step - loss: 0.4647 - accuracy: 1.0000
Epoch 9/500
1/1 [==============================] - 0s 7ms/step - loss: 0.4645 - accuracy: 1.0000
Epoch 10/500
1/1 [==============================] - 0s 8ms/step - loss: 0.4644 - accuracy: 1.0000
Epoch 11/500
1/1 [===========

In [47]:
print(model.layers[0].get_weights())

[array([[0.89355826],
       [0.8937424 ]], dtype=float32), array([-1.4598473], dtype=float32)]


In [48]:
model.predict(x)

array([[0.18849069],
       [0.36213607],
       [0.36209357],
       [0.58113956]], dtype=float32)

**Creating database for a XOR Gate**

In [56]:
x = [[0,0], [0,1], [1,0], [1,1]]
y = [[0], [1], [1], [0]]

In [69]:
xor= Sequential()
xor.add(Dense(2, input_dim=2, activation='sigmoid'))  # hidden layer with 2 neurons
xor.add(Dense(1, activation='sigmoid'))  # output layer with 1 neuron
xor.compile(optimizer='adam', loss='binary_crossentropy', metrics=["accuracy"])
xor.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_8 (Dense)              (None, 2)                 6         
_________________________________________________________________
dense_9 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


Add image 

In [71]:
xor.fit(x, y, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.6744 - accuracy: 0.5000
Epoch 2/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.6743 - accuracy: 0.5000
Epoch 3/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.6742 - accuracy: 0.5000
Epoch 4/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.6741 - accuracy: 0.5000
Epoch 5/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.6740 - accuracy: 0.5000
Epoch 6/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.6739 - accuracy: 0.5000
Epoch 7/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.6738 - accuracy: 0.5000
Epoch 8/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.6737 - accuracy: 0.5000
Epoch 9/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.6736 - accuracy: 0.5000
Epoch 10/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.6735 - accuracy: 0.5000
Epoch 11/1000
1/1 [

In [72]:
xor.get_weights()

[array([[ 3.252579 ,  2.7027147],
        [-3.5552826, -2.53739  ]], dtype=float32),
 array([-2.0127141,  1.567139 ], dtype=float32),
 array([[ 2.2657714],
        [-2.0680547]], dtype=float32),
 array([0.9046557], dtype=float32)]

In [74]:
xor.predict(x)

array([[0.36834455],
       [0.5853825 ],
       [0.65074575],
       [0.34320635]], dtype=float32)

**Deep Neural Network to Predict hand written Digit 
recognition**

In [76]:
## IMPORTING DATASET

from sklearn.datasets import load_breast_cancer
Data = load_breast_cancer()

In [79]:
print(Data.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [81]:
features = Data.data
target = Data.target

print(features.shape)
print(target.shape)

(569, 30)
(569,)


In [82]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2)

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(455, 30)
(455,)
(114, 30)
(114,)


In [83]:
from keras.models import Sequential
from keras.layers import Dense

In [86]:
model = Sequential()
model.add(Dense(32, input_dim = 30, activation='relu'))  ## hidden layer 1
model.add(Dense(64, activation='relu'))  ## hidden layer 2
model.add(Dense(1, activation='sigmoid'))

Add image (Deep Learning)

In [88]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [89]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 32)                992       
_________________________________________________________________
dense_4 (Dense)              (None, 64)                2112      
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 65        
Total params: 3,169
Trainable params: 3,169
Non-trainable params: 0
_________________________________________________________________


In [97]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
15/15 [==============================] - 0s 2ms/step - loss: 0.2407 - accuracy: 0.9121
Epoch 2/10
15/15 [==============================] - 0s 2ms/step - loss: 0.1934 - accuracy: 0.9407
Epoch 3/10
15/15 [==============================] - 0s 2ms/step - loss: 0.1654 - accuracy: 0.9297
Epoch 4/10
15/15 [==============================] - 0s 2ms/step - loss: 0.1822 - accuracy: 0.9297
Epoch 5/10
15/15 [==============================] - 0s 2ms/step - loss: 0.3113 - accuracy: 0.8857
Epoch 6/10
15/15 [==============================] - 0s 2ms/step - loss: 0.3365 - accuracy: 0.8967
Epoch 7/10
15/15 [==============================] - 0s 2ms/step - loss: 0.2612 - accuracy: 0.9143
Epoch 8/10
15/15 [==============================] - 0s 2ms/step - loss: 0.1765 - accuracy: 0.9231
Epoch 9/10
15/15 [==============================] - 0s 2ms/step - loss: 0.1744 - accuracy: 0.9363
Epoch 10/10
15/15 [==============================] - 0s 2ms/step - loss: 0.1572 - accuracy: 0.9385


In [98]:
scores = model.evaluate(X_test, y_test)
print(scores)  ## returns loss and accuracy

4/4 [==============================] - 0s 3ms/step - loss: 0.1513 - accuracy: 0.9386
[0.15125681459903717, 0.9385964870452881]


In [104]:
predictions = model.predict(X_test)
label=[]
for pred in predictions:
  if pred>=0.5:
    print("Malignant")
  else:
    print("Benign")

Benign
Malignant
Malignant
Benign
Malignant
Benign
Benign
Benign
Malignant
Malignant
Malignant
Malignant
Benign
Malignant
Malignant
Malignant
Benign
Malignant
Malignant
Malignant
Benign
Benign
Benign
Malignant
Malignant
Malignant
Malignant
Benign
Benign
Malignant
Benign
Benign
Malignant
Malignant
Benign
Malignant
Benign
Benign
Malignant
Malignant
Malignant
Benign
Benign
Malignant
Benign
Benign
Benign
Malignant
Malignant
Malignant
Benign
Benign
Benign
Malignant
Malignant
Benign
Benign
Malignant
Malignant
Malignant
Benign
Benign
Malignant
Malignant
Benign
Malignant
Benign
Malignant
Malignant
Malignant
Malignant
Malignant
Malignant
Malignant
Malignant
Malignant
Malignant
Malignant
Malignant
Malignant
Malignant
Benign
Malignant
Malignant
Malignant
Malignant
Malignant
Benign
Malignant
Benign
Benign
Malignant
Malignant
Malignant
Malignant
Malignant
Malignant
Benign
Malignant
Benign
Malignant
Malignant
Malignant
Benign
Malignant
Malignant
Benign
Malignant
Malignant
Malignant
Malignant
Benign
